name: Node.js Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-and-run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Or another version that your project uses

    - name: Install dependencies
      run: |
        npm install
        npx playwright install
      

    - name: Run the script
      run: |
        node index.js  # or node index.js if you want to run without the script
